"""created_at table added

Revision ID: e253b104c60a
Revises: 1ad79d56554e
Create Date: 2025-03-04 20:48:56.302082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e253b104c60a'
down_revision: Union[str, None] = '1ad79d56554e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'created_at')
    # ### end Alembic commands ###
